# NumPy and Vectorization
Because For-Loops are for dweebs.

In [1]:
import numpy as np
import time

In [6]:
a = np.zeros(4) # a 4-long vector of 0s; can also specify the shape here.
print(a, a.shape, a.dtype)
b = np.random.random_sample(4) # We can easily get random values between 0, 1
print(b)

[0. 0. 0. 0.] (4,) float64
[0.06869065 0.25407613 0.85490792 0.31731156]


In [10]:
# A shape tuple isn't taken by all functions
c = np.arange(4.)
print(c)
d = np.random.rand(4)
print(d)

[0. 1. 2. 3.]
[0.69066752 0.14278275 0.93393781 0.57184959]


In [14]:
# Or you can just...use your own values as we have been.
e = [1, 5, 3, 9]
f = np.array(e)
print(f)

[1 5 3 9]


## Operations

- Indexing and slicing, as with regular Python arrays.

In [16]:
# Single-operations
g = -f
print(g)
h = np.sum(f)
print(h)
i = np.mean(f)
print(i)
j = f ** 2
print(j)

[-1 -5 -3 -9]
18
4.5
[ 1 25  9 81]


In [18]:
# Element-wise operations for 2 vectors (requiring sizes to be the same)
a = np.array([1, 2, 3, 4])
b = np.array([-1, -2, 3, 4])

print(a + b)
print(a - b)
print(a * 5)
print(np.dot(a, b), np.dot(b, a))

[0 0 6 8]
[2 4 0 0]
[ 5 10 15 20]
20 20


In [33]:
# Demo of speed increase
np.random.seed(1)
a = np.random.rand(1_000_000)
b = np.random.rand(1_000_000)
start = time.time()
c = np.dot(a, b)
end = time.time()
fast = end - start
print(c, f"{fast: 0.4e}ms")

start = time.time()
total = 0
for i in range(len(a)):
    total += a[i] * b[i]
end = time.time()
slow = end - start
print(total, f"{slow: 0.4e}ms")

# Also note the slightly different outcomes; the loss of accuracy at some point
print(f"\nDifference Factor: Slow is taking {slow / fast : 4.4} times as long.")

del(a)
del(b)

249825.02337924895  2.3794e-04ms
249825.02337923684  2.4575e-01ms

Difference Factor: Slow is taking  1.033e+03 times as long.


## Matrices
Where it gets meaty.

In [37]:
np.array([[1],[2],[3]]).shape
a = np.zeros((1, 5))
print(a)
b = np.random.random((2, 4))
print(b) # 2 examples with 4 features each. m = 2, n = 4

[[0. 0. 0. 0. 0.]]
[[0.76850178 0.90838834 0.54804153 0.89855918]
 [0.03513744 0.09212483 0.86121123 0.50516394]]


In [40]:
# You can reshape vectors/arrays into matrices, and can pass in -1 to a size to have it 
# computed for you
# They can be sliced, too.
a = np.arange(6).reshape(-1, 2)
print(a)
print(a[1][1:])
print

[[0 1]
 [2 3]
 [4 5]]
